language: go
sudo: required

go:
    - 1.6

env:
    - KUBE_VERSION="v1.3.0-alpha.3"

services:
    - docker

before_install:
    - docker run     --volume=/:/rootfs:ro     --volume=/sys:/sys:ro     --volume=/var/lib/docker/:/var/lib/docker:rw     --volume=/var/lib/kubelet/:/var/lib/kubelet:rw     --volume=/var/run:/var/run:rw     --net=host     --pid=host     --privileged=true     --name=kubelet     -d     gcr.io/google_containers/hyperkube-amd64:${KUBE_VERSION}   /hyperkube kubelet         --containerized         --hostname-override="127.0.0.1"         --address="0.0.0.0"         --api-servers=http://localhost:8080         --config=/etc/kubernetes/manifests         --cluster-dns=10.0.0.10         --cluster-domain=cluster.local         --allow-privileged=true --v=2

install:
    #Add Godeps dependencies to GOPATH and PATH
    - export GOPATH="${TRAVIS_BUILD_DIR}/vendor:$GOPATH"
    - export PATH="${TRAVIS_BUILD_DIR}/vendor/bin:$PATH"

before_script:
    - go get -u github.com/tools/godep

script:
    - ./hack/test.sh 
