kind: Pod
apiVersion: v1
metadata:
  name: flower
spec:
  restartPolicy: Always
  containers:
  - name: flower
    image: gcr.io/bep-matosi/flower:1.0.3
    args:
    - -v=3
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:v1.2.4
    imagePullPolicy: Always
    args:
    - proxy
    - "-p"
    - '8080'
