kind: Pod
apiVersion: v1
metadata:
  name: flower
spec:
  restartPolicy: Always
  containers:
  - name: flower
    image: "gcr.io/nce-dsd2015/flower:1.0.7-stable"
    args:
    - -v=3
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:v1.2.4
    imagePullPolicy: Always
    args:
    - proxy
    - "-p"
    - '8080'
