apiVersion: "nerdalize.com/v1alpha1"
kind: "Workflow"
metadata:
  name: "test-workflow"
spec:
  activeDeadlineSeconds: 3600
  steps:
    step-a:
      jobTemplate:
        metadata:
          name: "job1"
        spec:
          parallelism: 1
          template:
            metadata:
              name: "pod1"
              annotations:
                scheduler.alpha.kubernetes.io/name: heat-scheduler
            spec:
              restartPolicy: "OnFailure"
              containers:
                -
                  image: "ubuntu"
                  name: "ubuntu1"
                  command:
                    - "/bin/sleep"
                    - "20"
    step-b:
      dependencies:
        - "step-a"
      jobTemplate:
        metadata:
          name: "job2"
        spec:
          parallelism: 1
          template:
            metadata:
              name: "pod2"
              annotations:
                scheduler.alpha.kubernetes.io/name: heat-scheduler
            spec:
              restartPolicy: "OnFailure"
              containers:
                -
                  image: "ubuntu"
                  name: "ubuntu2"
                  command:
                    - "/bin/sleep"
                    - "20"
    step-c:
      dependencies:
        - "step-b"
      jobTemplate:
        metadata:
          name: "job3"
        spec:
          parallelism: 1
          template:
            metadata:
              name: "pod3"
              annotations:
                scheduler.alpha.kubernetes.io/name: heat-scheduler
            spec:
              restartPolicy: "OnFailure"
              containers:
                -
                  image: "ubuntu"
                  name: "ubuntu3"
                  command:
                    - "/bin/sleep"
                    - "20"
    step-d:
      dependencies:
        - "step-b"
      jobTemplate:
        metadata:
          name: "job4"
        spec:
          parallelism: 1
          template:
            metadata:
              name: "pod4"
              annotations:
                scheduler.alpha.kubernetes.io/name: heat-scheduler
            spec:
              restartPolicy: "OnFailure"
              containers:
                -
                  image: "ubuntu"
                  name: "ubuntu4"
                  command:
                    - "/bin/sleep"
                    - "20"
    step-e:
      dependencies:
        - "step-b"
      jobTemplate:
        metadata:
          name: "job5"
        spec:
          parallelism: 1
          template:
            metadata:
              name: "pod5"
              annotations:
                scheduler.alpha.kubernetes.io/name: heat-scheduler
            spec:
              restartPolicy: "OnFailure"
              containers:
                -
                  image: "ubuntu"
                  name: "ubuntu5"
                  command:
                    - "/bin/sleep"
                    - "20"
    step-f:
      dependencies:
        - "step-c"
        - "step-d"
        - "step-e"
      jobTemplate:
        metadata:
          name: "job6"
        spec:
          parallelism: 1
          template:
            metadata:
              name: "pod6"
              annotations:
                scheduler.alpha.kubernetes.io/name: heat-scheduler
            spec:
              restartPolicy: "OnFailure"
              containers:
                -
                  image: "ubuntu"
                  name: "ubuntu6"
                  command:
                    - "/bin/sleep"
                    - "10"
